pkg/memtier/addrdata.go, pkg/memtier/addrdata_test.go
AddrDatas is a data structure that associates arbitrary data to non-overlapping address ranges. Iterating through this structure happens in the order of starting addresses. This change adds Sorted() function to the data structure that enables sorting the address ranges based on the data associated to them. For instance, if data is a timestamp of last access, Sorted() helps sorting ranges according to time since accessed.
=> Add Sorted() method to addrdata

pkg/memtier/tracker.go
Fix error on searching for the first overlapping address in the Flattened() function. Before this fix the search sometimes continued to addresses of another tracked process.
Fixes #4
=> trackers: fix panic on Flattened()

pkg/memtier/tracker_softdirty.go
This change makes the removePid logic similar in both softdirty and idlepage trackers.
=> tracker softdirty: remove access data on removing a pid

pkg/memtier/pidwatcher_cgroups.go, sample-configs/memtierd-age-idlepage-trackonly.yaml
Also raise a warning if cgroups config is missing for PidWatcherCgroups
examples:
root@vm> nohup sh -c 'socat tcp4-listen:5555,fork,reuseaddr - | memtierd -config memtierd.yaml -debug' > memtierd.output.txt 2>&1 & sleep 2; cat memtierd.output.txt
**WARN: memtier PidWatcherCgroups: cgroups config is missing**
memtierd> DEBUG: memtier TrackerSoftDirty: online
=> sample-configs: add example yaml for "filter" pidwatcher from cgroups

Makefile
Building meme with the -race flag changes memory consumption and access patterns of the process so that it will cause e2e tests to fail. This patch enables building everything simply with
make RACE=1
and running e2e tests with memtierd race detection on.
=> build: never build meme with race detection

test/e2e/memtierd.test-suite/no-policy/n4c16/test01-mover/code.var.sh
When building meme with make STATIC=1 DEBUG=1, memory size is bigger than expected in the e2e test. Allow a larger number of pageouts than previously.
=> e2e: fix mover test to work with a bigger meme

pkg/memtier/pidwatcher_cgroups.go, pkg/memtier/policy_ratio.go
Help detecting user errors by logging a warning if a directory in a cgroups pidwatcher configuration does not contain the cgroups.procs file. Do not log more than one warning on each bad directory path. This patch fixes a typo in the ratio policy debug print, too.
=> pidwatcher cgroups: log a warning on bad paths

pkg/memtier/prompt.go, test/e2e/memtierd.test-suite/no-policy/n4c16/test01-mover/code.var.sh
This PR fixes the issue that "mover -wait" might get called earlier than the mover starts handling new tasks.
In this case, "mover -wait" returns immediately as Paused as follows.
```bash
root@vm> offset=$(wc -l memtierd.output.txt | awk '{print $1+1}'); echo -e 'mover -config {"IntervalMs":10,"Bandwidth":5}\nswap -out -pids 40436 -mover\nmover -wait' | socat - tcp4:localhost:5555; sleep 1; tail -n+${offset} memtierd.output.txt
memtierd> memtierd> DEBUG: memtier Mover: online
memtierd> mover wait received: Paused
```
With the current PR, mover will first start handling new tasks, "swap -pid $PID -status" will not return anything until "mover -wait" returns "memtierd> mover wait received: AllDone". Thus, also increases the max waiting time for related e2e test cases because of the delay.
=> Delay calling mover.Wait when using mover with *wait flag

pkg/memtier/tracker_idlepage.go, pkg/memtier/tracker_softdirty.go
If a process got completely swapped out, trackers got only an empty list of address ranges and treated this as a signal of the whole process having disappeared. As a result, they effectively stopped tracking the process. Change the behavior so that only an error in reading address ranges means that the processes has disappeared, and in that case, remove also tracking counters of that process. That is, GetCounters() will return data only on processes that are thought to be running.
=> trackers: fix softdirty and idlepage sudden tracking stops

test/e2e/memtierd.test-suite/memtierd.source.sh
memtierd-meme-stop does not need to sleep unless it is removing the meme cgroup. The cgroup should be removed regardless of MEME_PID environment variable, but if removing it fails, it is not an error of stopping meme. In that case there might be something else running in the cgroup, and we will let them run. Memes got killed anyway.
=> e2e: always clean up meme cgroup if it was in use

test/e2e/memtierd.test-suite/policy-heat/n4c16/test02-move-idlepage/code.var.sh, test/e2e/memtierd.test-suite/thp.source.sh
The idlepage test failes if vm does not have THP enabled, or if meme has been built with make DEBUG=1. This patch fixes the first issue by making sure that THP is enabled, and the second issue by relaxing the amount of cold memory that is expected to be moved.
=> e2e: more robust heat/idlepage test

pkg/memtier/log.go
Expose logging controls to memtier package users.
These changes allow users (such as memtierd) to configure logging prefix and write their own messages to the same log.
=> log: enable modifying log prefix and writing to memtier log

cmd/memtierd/main.go, pkg/memtier/prompt.go, test/e2e/memtierd.test-suite/memtierd.source.sh
- Introduce three ways to run memtierd commands, any combination of which is allowed and makes perfect sense. In the order of execution the ways are: command line arguments (-c COMMANDS), command file (-f FILE) and the interactive prompt (--prompt).
- Show interactive prompt only if requested by the user (--prompt).
- Add logging into a file (-l FILE).
- Add option for echoing executed commands from any source (--echo).
- Drop --config-dump.
- Update the command line parameters with which memtierd is launched in e2e tests.
=> memtierd: redesign command line arguments

pkg/memtier/prompt.go, pkg/memtier/prompt_test.go
The log command writes messages to the memtier log from memtier commands. It also enables copying and capturing memtier prompt output to the log.
=> prompt: add the log command

pkg/memtier/prompt.go, pkg/memtier/prompt_test.go, test/e2e/memtierd.test-suite/no-policy/n4c16/test01-mover/code.var.sh, test/e2e/memtierd.test-suite/no-policy/n4c16/test02-tracker-finder/code.var.sh
Quotation and escaping in memtier prompt command parser enables command arguments to include whitespace. As the syntax is shell-like, parsing feels the same in both sides of piped prompt commands (MEMTIER-COMMAND | SHELL-COMMAND). Corresponding updates made to e2e tests.
=> prompt: add shell-like semantics to ', " and \ in commands

.github/workflows/common-verify-code.yaml
fix the remaining cyclomatic check issues might violate the readability and maintainability, thus, delete the cyclomatic check in ci currently
=> ci: disable cyclomatic check

cmd/memtierd/main.go, pkg/memtier/pidwatcher_proc.go, pkg/memtier/unmarshal.go
- Support json and yaml parser syntax and capitalization.
- Return errors from unmarshaling configurations with unknown fields.
- Improve error messages from memtierd -config issues.
=> memtierd: unknown fields in json and yaml are treated as errors

cmd/memtierd/main.go
"memtierd -c help" returned immediately eof without running the command.
=> memtierd: fix running single commands from command-line

go.mod
modify go version from 1.22 to 1.22.0 so that the following error could be avoided.
go: download go1.22 for linux/amd64: toolchain not available, Error: Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.16.3/x64/codeql/go/tools/autobuild.sh"
Changes have been tested with https://github.com/yanjing1104/memtierd/pull/7, codeql-scan passed successfully.
=> Fix the CI error fo "perform CodeQL Analysis"

pkg/memtier/prompt.go
Enable loading pidwatcher configuration from a file similarly to policy and tracker configuration.
=> prompt: add pidwatcher -config-file option

.github/workflows/common-verify-code.yaml, .golangci.yaml, Makefile, pkg/memtier/addrdata_test.go, pkg/memtier/madvise_linux.go, pkg/memtier/move_linux.go, pkg/memtier/policy_age.go, pkg/memtier/proc.go, pkg/memtier/prompt.go, pkg/memtier/prompt_test.go, pkg/memtier/tracker_softdirty.go, pkg/memtier/tracker_test.go
- Add configuration for golangci-lint.
- Disable all golangci-lint checkers that report errors at this point.
- Fix all empty-lines checker errors.
=> ci: replace golint with revive, fix emptylines

pkg/memtier/pidwatcher_filter.go, pkg/memtier/proc.go
- Replace "exclude" filter flag with logical "not: <filter>".
- Introduce logical "and: [filter...]" and "or: [filter...]".
- Add pid filtering based on minimal memory size, resident memory size, and private dirty memory size.
=> pidwatcher: structured pid filtering and new criteria

pkg/memtier/pidwatcher_filter.go
Polling the source pidwatcher will cause adding pids to the pidwatcher. Adding will need locking, so we cannot hold the lock when polling the source.
=> pidwatcher: fix deadlock in filter pidwatcher poll

cmd/memtierd/README.md
- ./cmd/memtierd/README.md:354: fliter ==> filter
=> fix spellcheck error

test/e2e/lib/distro.bash
apt daily updates timer causes unexpected locks in apt usage in tests. That causes false test failures.
=> e2e: remove daily system updates
